### ISSUE TITLE
您好！我是react native新手，希望能用您写的这个app练习一下，但在运行时出了一点问题。

### ISSUE THREAD

**Issue by Kinice** [caohongtao/raindrop-app#1]
我的android环境都配置好了，小demo（就是官方文档中的movie）也可以运行，我就按照您readme里的流程react-native run-android，结果报如下错误：

> A problem occurred evaluating project ':app'.
> Could not find property 'MYAPP_RELEASE_STORE_FILE' on SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=null}.

请问这是怎么回事？网上搜不到结果，是因为签名的问题吗？
如果您有时间，希望能回答一下！十分感谢！

**Comment by caohongtao** [comment]
确实是签名的问题，需要配置gradle。
可以参考官方的文档：https://facebook.github.io/react-native/docs/signed-apk-android.html
